package iokit

// Code generated by mocker. DO NOT EDIT.

import (
	"github.com/ctx42/testing/pkg/mock"
	"github.com/ctx42/testing/pkg/tester"
)

type ReadCloserMock struct {
	*mock.Mock
	t tester.T
}

func NewReadCloserMock(t tester.T) *ReadCloserMock {
	t.Helper()
	return &ReadCloserMock{Mock: mock.NewMock(t), t: t}
}

func (_mck *ReadCloserMock) Read(p []byte) (int, error) {
	_mck.t.Helper()
	_args := []any{p}
	_rets := _mck.Called(_args...)
	if len(_rets) != 2 {
		_mck.t.Fatal("the number of mocked method returns does not match")
	}

	var _r0 int
	if _rFn, ok := _rets.Get(0).(func([]byte) int); ok {
		_r0 = _rFn(p)
	} else if _r := _rets.Get(0); _r != nil {
		_r0 = _r.(int)
	}
	var _r1 error
	if _rFn, ok := _rets.Get(1).(func([]byte) error); ok {
		_r1 = _rFn(p)
	} else if _r := _rets.Get(1); _r != nil {
		_r1 = _r.(error)
	}
	return _r0, _r1
}

func (_mck *ReadCloserMock) OnRead(p any) *mock.Call {
	_mck.t.Helper()
	_args := []any{p}
	return _mck.On("Read", _args...)
}

func (_mck *ReadCloserMock) Close() error {
	_mck.t.Helper()
	var _args []any
	_rets := _mck.Called(_args...)
	if len(_rets) != 1 {
		_mck.t.Fatal("the number of mocked method returns does not match")
	}

	var _r0 error
	if _rFn, ok := _rets.Get(0).(func() error); ok {
		_r0 = _rFn()
	} else if _r := _rets.Get(0); _r != nil {
		_r0 = _r.(error)
	}
	return _r0
}

func (_mck *ReadCloserMock) OnClose() *mock.Call {
	_mck.t.Helper()
	var _args []any
	return _mck.On("Close", _args...)
}
